server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kyriemtx/spring-cloud-microservice-study.git
          search-paths: config-repo   #配置仓库地址
          username: kyriemtx
          password: nan951208


