eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
server:
  port: 8085
spring:
  application:
    name: microservice-zuul
zuul:
  routes:
    api-r:
      path: /api-r/**
      serviceId: microservice-consumer-movie-ribbon-with-hystrix
    api-f:
      path: /api-f/**
      serviceId: microservice-consumer-movie-feign

